<?php require 'template/layout/header.phtml' ?>
<form action="edit" method="POST">
    <label>Ice cream parlor name
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Ice cream parlor name" aria-label="Username"  name="name_heladeria" aria-describedby="basic-addon1">
    </div>
    </label>
    <label>Ice cream parlor address
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Ice cream parlor addres" aria-label="Username"  name="address" aria-describedby="basic-addon1">
    </div>
    </label>
    <label>Ice cream parlor association date
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Ice cream parlor association date" aria-label="Username"  name="association_date" aria-describedby="basic-addon1">
    </div>
    </label>
    <label>Illustrative image
        <figure>
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Illustrative image" aria-label="Username"  name="illustrative_image" aria-describedby="basic-addon1">
            </div>
        </figure>
    </label>
</form>
<?php require 'template/layout/footer.phtml' ?>