<?php require 'templates/layout/header.phtml' ?>
<form action="addIceCream" method="POST">
    <label>Ice cream name
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Name of ice cream" aria-label="Username"  name="name_helado" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Subcategory
    <select name="Subcategory" class="form-select" aria-label="Default select example">
        <option selected>Chocolate</option>
        <option value="Chocolate">Chocolate</option>
        <option value="Crema">Crema</option>
        <option value="Crema Especial">Crema Especial</option>
        <option value="Dulce De Leche">Dulce De Leche</option>
        <option value="Frutales">Frutales</option>
    </select>
    </label>
    <label>Weight
        <div class="input-group mb-3">
            <input type="number" class="form-control" placeholder="Weight" aria-label="Username"  name="weight" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Price cost
        <div class="input-group mb-3">
            <input type="number" class="form-control" placeholder="Price cost" aria-label="Username"  name="price_cost" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Price sale
        <div class="input-group mb-3">
            <input type="number" class="form-control" placeholder="Price sale" aria-label="Username"  name="price_sale" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Heladeria
        <select name="id_heladeria" class="form-select" aria-label="Default select example">
        <?php foreach ($options as $value => $label): ?>
            <option value="<?= $value ?>" <?= ($value == $default) ? 'selected' : ''; ?>>
                <?= $label ?>
            </option>
        <?php endforeach; ?>
        </select>
    </label>
    <label>Illustrative image
        <figure>
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Illustrative image" aria-label="Username"  name="illustrative_image" aria-describedby="basic-addon1">
            </div>
        </figure>
    </label>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
<?php require 'templates/layout/footer.phtml' ?>