<?php require 'template/layout/header.phtml' ?>
<form action="add" method="POST">
    <label>Ice cream parlor id
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Ice cream parlor id" aria-label="Username"  name="id_heladeria" aria-describedby="basic-addon1">
        </div>
    </label> 
    <label>Ice cream name
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Name of ice cream" aria-label="Username"  name="name_helado" aria-describedby="basic-addon1">
        </div>
    </label>
    <select class="form-select" aria-label="Default select example">
        <option selected>Subcategory</option>
        <option value="Chocolate">Chocolate</option>
        <option value="Crema">Crema</option>
        <option value="Crema Especial">Crema Especial</option>
        <option value="Dulce De Leche">Dulce De Leche</option>
        <option value="Frutales">Frutales</option>
    </select>
    <label>Weight
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Weight" aria-label="Username"  name="weight" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Price cost
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Price cost" aria-label="Username"  name="price_cost" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Price sale
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Price sale" aria-label="Username"  name="price_sale" aria-describedby="basic-addon1">
        </div>
    </label>
    <label>Heladeria id
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Id of heladeria" aria-label="Username"  name="id_heladeria" aria-describedby="basic-addon1">
        </div>
    </label>
    <!-- leer las posiblidades (nombre/id) -->
</form>
<?php require 'template/layout/footer.phtml' ?>