<?php require 'templates/layout/header.phtml' ?>
<ul class="list-group">
  <?php foreach ($iceCreams as $icecream): ?>
      <li class="list-group-item">
          <?php $iceCreamParlor =  htmlspecialchars($icecream->ID_Heladerias); ?> 
          <b><?= htmlspecialchars($icecream->Nombre) ?></b> | <b><?= htmlspecialchars($icecream->Peso) ?></b> | <b><?= htmlspecialchars($icecream->Precio_Venta) ?></b> |<b><a href="returnIceCream/<?= htmlspecialchars($iceCreamParlor) ?>"></a></b> 
          <!-- opciones de administrador -->
          <?php if(isset($_SESSION['Usuario'])): ?> 
            <a href="showEditIceCream/<?=$icecream->ID_Helados ?>" type="button" class="btn btn-outline-warning">Edit</a>
            <a href="deleteIceCream/<?=$icecream->ID_Helados ?>" type="button" class="btn btn-outline-danger">Delete</a>
          <?php endif ?> 
          <a href="detailsIceCream/<?=$icecream->ID_Helados ?>" type="button" class="btn btn-outline-info">Details</a>
      </li>
     <?php endforeach ?> 
</ul>
<?php require 'templates/layout/footer.phtml' ?>