<?php require 'templates/layout/header.phtml' ?>
<ul class="list-group">
  <?php foreach ($iceCreamParlor as $icecream): ?>
      <li class="list-group-item">
        <!--muestro todos los items incluida la imagen teniendo en cuenta ENT_QUOTES para prevenir errores en comillas simples-->
        <b><?= htmlspecialchars($icecream->Nombre) ?></b> | <b><?= htmlspecialchars($icecream->Direccion) ?></b> | <b><?= htmlspecialchars($icecream->Fecha_Asociacion) ?></b>
      </li>
      <?php if(isset($_SESSION['Usuario'])): ?> 
            <a href="UpdateIceCreamParlor/<?= $icecream->ID_Heladerias ?>" type="button" class="btn btn-outline-warning">Edit</a>
            <a href="deleteIceCreamParlor/<?= $icecream->ID_Heladerias ?>" type="button" class="btn btn-outline-danger">Delete</a>
      <?php endif ?>
      <a href="detailsIceCreamParlor/<?= $icecream->ID_Heladerias?>" type="button" class="btn btn-outline-info">See more</a>
      <?php endforeach ?> 
</ul>
<?php require 'templates/layout/footer.phtml' ?>
