<?php require 'templates/layout/header.phtml' ?>
<ul class="list-group">
    <b><?= htmlspecialchars($iceCreamParlor->Nombre) ?></b><b><?= htmlspecialchars($iceCreamParlor->Direccion) ?></b><b><?= htmlspecialchars($iceCreamParlor->Fecha_Asociacion) ?></b><figure><img src="<?=$iceCreamParlor->Foto_Heladerias?>"></figure>
                                                                                                                                                                                        
    <?php foreach ($iceCreams as $icecream): ?>
      <li class="list-group-item">
        <b><?= htmlspecialchars($icecream->Nombre) ?></b> | <b><?= htmlspecialchars($icecream->Peso) ?></b> | <b><?= htmlspecialchars($icecream->Precio_Venta) ?></b>
      </li>
    <?php endforeach ?> 
</ul>
<?php require 'templates/layout/footer.phtml' ?>