<?php require 'templates/layout/header.phtml'?>
<ul class="list-group">
      <li class="list-group-item">
      <!--muestro todos los items incluida la imagen-->
      <b><?= htmlspecialchars($iceCreams->Nombre) ?></b> | <b><?=$iceCreams->Subcategorias ?></b> | <b><?= htmlspecialchars($iceCreams->Peso) ?></b> | <b><?= htmlspecialchars($iceCreams->Precio_Costo) ?></b> | <b><?= htmlspecialchars($iceCreams->Precio_Venta) ?> | <figure><img src="<?=$iceCreams->Foto_Helados ?>"><figure>
      </li>
      <p>Ice creamparlor<p>
      <li>
         <b><?= htmlspecialchars($iceCreamParlor->Nombre) ?></b> | <b><? htmlspecialchars($iceCreamParlor->Direccion)?></b> | <b><? htmlspecialchars($iceCreamParlor->Fecha_Asociacion) ?></b>
      </li>
</ul>
<?php require 'templates/layout/footer.phtml'?>
