<?php require 'template/layout/header.phtml' ?>
<ul class="list-group">
  <?php foreach ($iceCreams as $icecream): ?>
      <li class="list-group-item">
          <?php $iceCreamParlor = htmlspecialchars($icecream->ID_Heladerias); ?> 
          <b><?= htmlspecialchars($icecream->Nombre) ?></b> | <b><?= htmlspecialchars($icecream->Peso) ?></b> | <b><?= htmlspecialchars($icecream->Precio_Venta) ?></b> |<b><a href="returnIceCream/<?= htmlspecialchars($iceCreamParlor) ?>"></a></b> 
          <!-- opciones de administrador -->
          <?php if(session_status() === PHP_SESSION_ACTIVE) ?> {
            <a href="editIceCream/<?= $icecream->ID_Helados ?>" type="button" class="btn btn-outline-warning">Edit></a>
            <a href="deleteIceCream/<?= $icecream->ID_Helados ?>" type="button" class="btn btn-outline-danger">Delete</a>
          }
          <a href="detailsIceCream/<?= $icecream->ID_Helados ?>" type="button" class="btn btn-outline-info">Details></a>
      </li>
     <?php endforeach ?> 
</ul>
<?php require 'template/layout/footer.phtml' ?>